package test

/*
This file is generated by protoc-gen-gopherjs, DO NOT EDIT.
*/

import "github.com/gopherjs/gopherjs/js"

type MyMessage struct {
    *js.Object
    Msg string `js:"msg"`
    Num uint32 `js:"num"`
}
