required = [
  "github.com/onsi/ginkgo/ginkgo",
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/gopherjs/gopherjs",
]

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/gopherjs"

[[constraint]]
  name = "github.com/improbable-eng/grpc-web"
  version = "0.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/ginkgo"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/gomega"

[[constraint]]
  branch = "master"
  name = "github.com/rusco/qunit"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  branch = "master"
  name = "github.com/sclevine/agouti"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[constraint]]
  branch = "master"
  name = "honnef.co/go/js/dom"
