// Code generated by protoc-gen-gopherjs. DO NOT EDIT.
// source: wrappers/wrappers.proto

/*
Package wrappers is a generated protocol buffer package.

It is generated from these files:
	wrappers/wrappers.proto

It has these top-level messages:
	DoubleValue
	FloatValue
	Int64Value
	UInt64Value
	Int32Value
	UInt32Value
	BoolValue
	StringValue
	BytesValue
*/
package wrappers

import js "github.com/gopherjs/gopherjs/js"
import grpcweb "github.com/johanbrandhorst/gopherjs-improbable-grpc-web"

// Wrapper message for `double`.
//
// The JSON representation for `DoubleValue` is JSON number.
type DoubleValue struct {
	*js.Object
}

// NewDoubleValue creates a new DoubleValue.
// The double value.
func NewDoubleValue(value float64) *DoubleValue {
	m := &DoubleValue{
		Object: js.Global.Get("proto").Get("google").Get("protobuf").Get("DoubleValue").New([]interface{}{
			value,
		}),
	}

	return m
}

// GetValue gets the Value of the DoubleValue.
// The double value.
func (m *DoubleValue) GetValue() float64 {
	return m.Call("getValue").Float()
}

// SetValue sets the Value of the DoubleValue.
// The double value.
func (m *DoubleValue) SetValue(v float64) {
	m.Call("setValue", v)
}

func (m *DoubleValue) serialize() (rawBytes []byte, err error) {
	return grpcweb.Serialize(m)
}

func deserializeDoubleValue(rawBytes []byte) (*DoubleValue, error) {
	obj, err := grpcweb.Deserialize(js.Global.Get("proto").Get("google").Get("protobuf").Get("DoubleValue"), rawBytes)
	if err != nil {
		return nil, err
	}

	return &DoubleValue{
		Object: obj,
	}, nil
}

// Wrapper message for `float`.
//
// The JSON representation for `FloatValue` is JSON number.
type FloatValue struct {
	*js.Object
}

// NewFloatValue creates a new FloatValue.
// The float value.
func NewFloatValue(value float32) *FloatValue {
	m := &FloatValue{
		Object: js.Global.Get("proto").Get("google").Get("protobuf").Get("FloatValue").New([]interface{}{
			value,
		}),
	}

	return m
}

// GetValue gets the Value of the FloatValue.
// The float value.
func (m *FloatValue) GetValue() float32 {
	return float32(m.Call("getValue").Float())
}

// SetValue sets the Value of the FloatValue.
// The float value.
func (m *FloatValue) SetValue(v float32) {
	m.Call("setValue", v)
}

func (m *FloatValue) serialize() (rawBytes []byte, err error) {
	return grpcweb.Serialize(m)
}

func deserializeFloatValue(rawBytes []byte) (*FloatValue, error) {
	obj, err := grpcweb.Deserialize(js.Global.Get("proto").Get("google").Get("protobuf").Get("FloatValue"), rawBytes)
	if err != nil {
		return nil, err
	}

	return &FloatValue{
		Object: obj,
	}, nil
}

// Wrapper message for `int64`.
//
// The JSON representation for `Int64Value` is JSON string.
type Int64Value struct {
	*js.Object
}

// NewInt64Value creates a new Int64Value.
// The int64 value.
func NewInt64Value(value int64) *Int64Value {
	m := &Int64Value{
		Object: js.Global.Get("proto").Get("google").Get("protobuf").Get("Int64Value").New([]interface{}{
			value,
		}),
	}

	return m
}

// GetValue gets the Value of the Int64Value.
// The int64 value.
func (m *Int64Value) GetValue() int64 {
	return m.Call("getValue").Int64()
}

// SetValue sets the Value of the Int64Value.
// The int64 value.
func (m *Int64Value) SetValue(v int64) {
	m.Call("setValue", v)
}

func (m *Int64Value) serialize() (rawBytes []byte, err error) {
	return grpcweb.Serialize(m)
}

func deserializeInt64Value(rawBytes []byte) (*Int64Value, error) {
	obj, err := grpcweb.Deserialize(js.Global.Get("proto").Get("google").Get("protobuf").Get("Int64Value"), rawBytes)
	if err != nil {
		return nil, err
	}

	return &Int64Value{
		Object: obj,
	}, nil
}

// Wrapper message for `uint64`.
//
// The JSON representation for `UInt64Value` is JSON string.
type UInt64Value struct {
	*js.Object
}

// NewUInt64Value creates a new UInt64Value.
// The uint64 value.
func NewUInt64Value(value uint64) *UInt64Value {
	m := &UInt64Value{
		Object: js.Global.Get("proto").Get("google").Get("protobuf").Get("UInt64Value").New([]interface{}{
			value,
		}),
	}

	return m
}

// GetValue gets the Value of the UInt64Value.
// The uint64 value.
func (m *UInt64Value) GetValue() uint64 {
	return m.Call("getValue").Uint64()
}

// SetValue sets the Value of the UInt64Value.
// The uint64 value.
func (m *UInt64Value) SetValue(v uint64) {
	m.Call("setValue", v)
}

func (m *UInt64Value) serialize() (rawBytes []byte, err error) {
	return grpcweb.Serialize(m)
}

func deserializeUInt64Value(rawBytes []byte) (*UInt64Value, error) {
	obj, err := grpcweb.Deserialize(js.Global.Get("proto").Get("google").Get("protobuf").Get("UInt64Value"), rawBytes)
	if err != nil {
		return nil, err
	}

	return &UInt64Value{
		Object: obj,
	}, nil
}

// Wrapper message for `int32`.
//
// The JSON representation for `Int32Value` is JSON number.
type Int32Value struct {
	*js.Object
}

// NewInt32Value creates a new Int32Value.
// The int32 value.
func NewInt32Value(value int32) *Int32Value {
	m := &Int32Value{
		Object: js.Global.Get("proto").Get("google").Get("protobuf").Get("Int32Value").New([]interface{}{
			value,
		}),
	}

	return m
}

// GetValue gets the Value of the Int32Value.
// The int32 value.
func (m *Int32Value) GetValue() int32 {
	return int32(m.Call("getValue").Int())
}

// SetValue sets the Value of the Int32Value.
// The int32 value.
func (m *Int32Value) SetValue(v int32) {
	m.Call("setValue", v)
}

func (m *Int32Value) serialize() (rawBytes []byte, err error) {
	return grpcweb.Serialize(m)
}

func deserializeInt32Value(rawBytes []byte) (*Int32Value, error) {
	obj, err := grpcweb.Deserialize(js.Global.Get("proto").Get("google").Get("protobuf").Get("Int32Value"), rawBytes)
	if err != nil {
		return nil, err
	}

	return &Int32Value{
		Object: obj,
	}, nil
}

// Wrapper message for `uint32`.
//
// The JSON representation for `UInt32Value` is JSON number.
type UInt32Value struct {
	*js.Object
}

// NewUInt32Value creates a new UInt32Value.
// The uint32 value.
func NewUInt32Value(value uint32) *UInt32Value {
	m := &UInt32Value{
		Object: js.Global.Get("proto").Get("google").Get("protobuf").Get("UInt32Value").New([]interface{}{
			value,
		}),
	}

	return m
}

// GetValue gets the Value of the UInt32Value.
// The uint32 value.
func (m *UInt32Value) GetValue() uint32 {
	return uint32(m.Call("getValue").Int())
}

// SetValue sets the Value of the UInt32Value.
// The uint32 value.
func (m *UInt32Value) SetValue(v uint32) {
	m.Call("setValue", v)
}

func (m *UInt32Value) serialize() (rawBytes []byte, err error) {
	return grpcweb.Serialize(m)
}

func deserializeUInt32Value(rawBytes []byte) (*UInt32Value, error) {
	obj, err := grpcweb.Deserialize(js.Global.Get("proto").Get("google").Get("protobuf").Get("UInt32Value"), rawBytes)
	if err != nil {
		return nil, err
	}

	return &UInt32Value{
		Object: obj,
	}, nil
}

// Wrapper message for `bool`.
//
// The JSON representation for `BoolValue` is JSON `true` and `false`.
type BoolValue struct {
	*js.Object
}

// NewBoolValue creates a new BoolValue.
// The bool value.
func NewBoolValue(value bool) *BoolValue {
	m := &BoolValue{
		Object: js.Global.Get("proto").Get("google").Get("protobuf").Get("BoolValue").New([]interface{}{
			value,
		}),
	}

	return m
}

// GetValue gets the Value of the BoolValue.
// The bool value.
func (m *BoolValue) GetValue() bool {
	return m.Call("getValue").Bool()
}

// SetValue sets the Value of the BoolValue.
// The bool value.
func (m *BoolValue) SetValue(v bool) {
	m.Call("setValue", v)
}

func (m *BoolValue) serialize() (rawBytes []byte, err error) {
	return grpcweb.Serialize(m)
}

func deserializeBoolValue(rawBytes []byte) (*BoolValue, error) {
	obj, err := grpcweb.Deserialize(js.Global.Get("proto").Get("google").Get("protobuf").Get("BoolValue"), rawBytes)
	if err != nil {
		return nil, err
	}

	return &BoolValue{
		Object: obj,
	}, nil
}

// Wrapper message for `string`.
//
// The JSON representation for `StringValue` is JSON string.
type StringValue struct {
	*js.Object
}

// NewStringValue creates a new StringValue.
// The string value.
func NewStringValue(value string) *StringValue {
	m := &StringValue{
		Object: js.Global.Get("proto").Get("google").Get("protobuf").Get("StringValue").New([]interface{}{
			value,
		}),
	}

	return m
}

// GetValue gets the Value of the StringValue.
// The string value.
func (m *StringValue) GetValue() string {
	return m.Call("getValue").String()
}

// SetValue sets the Value of the StringValue.
// The string value.
func (m *StringValue) SetValue(v string) {
	m.Call("setValue", v)
}

func (m *StringValue) serialize() (rawBytes []byte, err error) {
	return grpcweb.Serialize(m)
}

func deserializeStringValue(rawBytes []byte) (*StringValue, error) {
	obj, err := grpcweb.Deserialize(js.Global.Get("proto").Get("google").Get("protobuf").Get("StringValue"), rawBytes)
	if err != nil {
		return nil, err
	}

	return &StringValue{
		Object: obj,
	}, nil
}

// Wrapper message for `bytes`.
//
// The JSON representation for `BytesValue` is JSON string.
type BytesValue struct {
	*js.Object
}

// NewBytesValue creates a new BytesValue.
// The bytes value.
func NewBytesValue(value []byte) *BytesValue {
	m := &BytesValue{
		Object: js.Global.Get("proto").Get("google").Get("protobuf").Get("BytesValue").New([]interface{}{
			value,
		}),
	}

	return m
}

// GetValue gets the Value of the BytesValue.
// The bytes value.
func (m *BytesValue) GetValue() []byte {
	return m.Call("getValue").Interface().([]byte)
}

// SetValue sets the Value of the BytesValue.
// The bytes value.
func (m *BytesValue) SetValue(v []byte) {
	m.Call("setValue", v)
}

func (m *BytesValue) serialize() (rawBytes []byte, err error) {
	return grpcweb.Serialize(m)
}

func deserializeBytesValue(rawBytes []byte) (*BytesValue, error) {
	obj, err := grpcweb.Deserialize(js.Global.Get("proto").Get("google").Get("protobuf").Get("BytesValue"), rawBytes)
	if err != nil {
		return nil, err
	}

	return &BytesValue{
		Object: obj,
	}, nil
}
